import type { Metadata } from "next";
import Head from "next/head";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

import { localization } from "@/utils";

import { abel, acme } from "@/config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      localization={localization}
      appearance={{
        cssLayerName: "clerk",
      }}
      waitlistUrl="/waitlist"
      afterSignOutUrl="/sign-in"
      // clerkJSVariant="headless"
    >
      <html lang="en" className={`${abel.variable} ${acme.variable}`}>
        <Head>
          <link rel="icon" href="/favicon.ico" type="image/png" />
          <meta name="theme-color" content="#ffffff" />
          <meta name="description" content="Travel Landing Page" />
        </Head>
        <body className={`${abel.variable} ${acme.variable} antialiased`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
