import type { Metadata } from "next";
import Head from "next/head";
import { ClerkProvider } from "@clerk/nextjs";
import "@/themes/globals.css";

import { localization } from "@/utils";
import { abel, acme } from "@/config";
import { Footer, Header } from "@/components";
import { ThemeProvider } from "@/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      localization={localization}
      appearance={{
        cssLayerName: "clerk",
      }}
      afterSignOutUrl="/sign-in"
    >
      <html lang="en" suppressHydrationWarning>
        <Head>
          <link rel="icon" href="/favicon.ico" type="image/png" />
          <meta name="theme-color" content="#ffffff" />
          <meta name="description" content="Travel Landing Page" />
        </Head>
        <body className={`${abel.variable} ${acme.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className="flex flex-col items-center justify-center h-fit">{children}</div>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
