import type { Metadata } from "next";
import Head from "next/head";
import { ClerkProvider } from "@clerk/nextjs";
import "@/themes/theme.css";

import { LOCALIZATION } from "@/constants/localization";
import { abel } from "@/config/fonts";
import { Toaster } from "@/components/ui/sonner";
import SessionWatcher from "@/components/SessionWatcher";

import { ThemeProvider } from "@/themes/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="icon" href="/favicon.ico" type="image/png" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="description" content="Travel Landing Page" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={`${abel.variable} antialiased`}>
        <ClerkProvider
          publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
          localization={LOCALIZATION}
          appearance={{
            cssLayerName: "clerk",
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <SessionWatcher />
            <Toaster theme="light" closeButton richColors />
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
